### ISSUE TITLE
恐らくどこにもアクセスできない状態になります

### ISSUE THREAD

**Issue by yobai909** [nodaguti/userChrome.js#1]
fox20.0.1 adblock#.uc.jsを使わせていただきました
フィルターの変換もしくは設定が間違っているのかWhite Listに入れない限りどこにもアクセスできなくなりました
リストは今までAdBlock Plusで使ってきた以下のものを順番に変換して追加してゆきました

Easy List
https://easylist-downloads.adblockplus.org/easylist.txt
日本向けフィルタ(仮)
http://tofukko.r.ribbon.to/abp.html
Japanese Site Adblock Filter
http://qme.mydns.jp/
何がまずかったご指摘いただけると助かります
よろしくおねがいします

**Comment by nodaguti** [comment]
回答が遅れて申し訳ありません。

ホワイトリストに追加しないとアクセスできないようになったということは、
ブラックリストのどこかに「全てのページにマッチするフィルタ」が含まれていると考えられます。
変換後のフィルタをもう一度ご確認下さい。

**Comment by nodaguti** [comment]
時間が経っているので close とさせていただきます．
